Resolve #192 "Custom power generator (solar panel?) building guide"
satisfactorymodding/Documentation pull request #253
Opened 2023-10-05 15:33 UTC by ARtemachka

Feel free to check and leave comments/suggestions.

2023-10-06 02:21 UTC, budak7273 requested changes
See the [discord](https://discord.com/channels/555424930502541343/1036634533077979146/1159671730609078312) discussion

2023-10-09 06:58 UTC, ARtemachka reviewed
Everything else looks good so you can submit after these are fixed.

2023-10-09 06:58 UTC, ARtemachka commented on modules/ROOT/pages/Development/BeginnersGuide/SimpleMod/machines/SolarPanel.adoc
> +Since as our Solar Panel does not require the custom behaviors of any of these, we will not use them.
> **_Since as_** our Solar Panel

It's redundant to have both, remove one of these.

2023-10-09 06:58 UTC, ARtemachka commented on modules/ROOT/pages/Development/BeginnersGuide/SimpleMod/machines/SolarPanel.adoc
> +as we need to connect our Solar Panel to the power lines to use its generated power to.
> to use its generated power **_to_**.

Remove.

2023-10-09 06:58 UTC, ARtemachka commented on modules/ROOT/pages/Development/BeginnersGuide/SimpleMod/machines/SolarPanel.adoc
> +This value defaults to the value we set in in our building,
> the value we set in **_in_** our building

Remove.

2023-10-09 06:58 UTC, ARtemachka commented on modules/ROOT/pages/Development/BeginnersGuide/SimpleMod/machines/SolarPanel.adoc
> +Next, we first need to figure out whether it's day or night and adjust power production accordingly.
> Next, we **_first_** need

Remove.

2023-10-09 06:58 UTC, ARtemachka commented on modules/ROOT/pages/Development/BeginnersGuide/SimpleMod/machines/SolarPanel.adoc
> +We can avoid repeating outselves here and use the parent class `Get Default Power Production Capacity` method
> avoid repeating **_outselves_** here

Ou**r**selves.

2023-10-09 07:40 UTC, budak7273 approved these changes

2023-10-09 07:40 UTC, merged