Update with changes from Dev
satisfactorymodding/Documentation pull request #267
Opened 2023-12-10 00:09 UTC by budak7273

2023-12-10 00:37 UTC, budak7273 commented
Closes #180

2023-12-16 21:18 UTC, budak7273 reviewed
Reviewed

2023-12-17 17:46 UTC, mircearoata requested changes

2023-12-17 17:46 UTC, mircearoata commented on modules/ROOT/pages/Development/Satisfactory/CustomLevels.adoc
> +  Make sure your Project Settings have FGWorldSettings as the World Settings Class.
Some casing issues/typos in this section

2023-12-17 17:46 UTC, mircearoata commented on modules/ROOT/pages/ForUsers/ConfiguringMods.adoc
> +Most using the SML Configuration System can have their configuration edited in-game
```suggestion
Mods using the SML Configuration System can have their configuration edited in-game
```

2023-12-17 17:46 UTC, mircearoata commented on modules/ROOT/pages/ForUsers/SatisfactoryModManager.adoc
> +https://github.com/satisfactorymodding/SatisfactoryModLauncher/releases[GitHub]!
```suggestion
https://github.com/satisfactorymodding/SatisfactoryModManager[GitHub]!
```

2023-12-18 16:55 UTC, mircearoata approved these changes

2023-12-18 16:55 UTC, merged