feat: Wwise documentation
satisfactorymodding/Documentation pull request #359
Opened 2024-12-31 23:32 UTC by mrhid6

2025-01-07 02:23 UTC, budak7273 requested changes
Looks nice on a brief read through, will check the reading flow flow in the compiled docs later when I can. A few comments

2025-01-07 02:23 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +You can update audio values using RTPC (Game Parameters).
what does RTPC stand for? it sounds like Game Parameters is part of the Unreal asset side of things

2025-01-07 02:23 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +image:Satisfactory/Wwise/Wwise_Image1.png[Wwise_Image1, 350]
Could you rename the image files to talk about what they are showcasing? Numbered file names is troublesome as inevitably another one will be added in the middle of the sequence

2025-01-07 02:23 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
What considerations need to be made for source control? I think the wwise project is currently excluded from git, and that will need to be changed on the SML side eventually. What is the RP team doing?

2025-01-07 09:35 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +You can update audio values using RTPC (Game Parameters).
Updated with better explaination on what RTPC means and clearer understanding of what it does.

2025-01-07 09:35 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +image:Satisfactory/Wwise/Wwise_Image1.png[Wwise_Image1, 350]
Renamed images for better understanding.

2025-01-07 09:46 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
We are currently adding the Wwise project to a separate repo. This contains all the source `.wav` files and all the settings for our audio. We are using Git LFS to store the larger files like the `.wav` files as per Wwise recommendations here: 

[Using Wwise with your source control system](https://www.audiokinetic.com/en/library/edge/?source=Help&id=using_wwise_with_source_control_system)

I recommend that SML create a new repo for the Wwise project that contains the Stubs and other info from the CSS audio team. Then, as part of the SML toolkit setup, this has to be pulled into the project. Then, if the mod dev uses Wwise, they can just change the git remote to their repo URL.

2025-01-07 17:19 UTC, budak7273 requested changes
Additional comments from a closer read through. Done via GH web so it might have broken formatting on accident.

2025-01-07 17:19 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +You can set up an RTPC in Wwise and Unreal and update the value in your building's blueprint.
```suggestion
Wwise uses a feature called Real-Time Parameter Control (RTPC) that allows game engines like Unreal or Unity to change values on Wwise assets in real-time.
This enables special behaviors like a manufacturing building's sound volume to fluctuate based on recipe progress.

After setting up RTPC in Wwise and Unreal, blueprint code can update audio parameter values.
```

2025-01-07 17:19 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +Open the newly created Game Parameter, and you should see the following in the main section.
```suggestion
Open the newly created Game Parameter, and you should see the following in the main section:
```

2025-01-07 17:19 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +You will need to set the range. I recommend using 0 to 1.
```suggestion
The parameter must have a range defined.
A useful range is `0.0` to `1.0` since many existing gameand engine systems already use that range as a start-finish, minimum-maximum, or off-on scale.
```

2025-01-07 17:19 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +Open your Audio and go to the `RTPC` tab. Click the `>>` in the main section to set what you want to update. In this case, I want to update the `Voice Volume`.
```suggestion
Open your Audio in Wwise and go to the `RTPC` tab.
Click the `>>` in the main section to set what you want to update.
This example case shows updating the `Voice Volume`.
```

2025-01-07 17:19 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
```suggestion
== Wwise and Source Control

[NOTE]
====
This heading is a work in progress.
The SML team plans to ship a Wwise project that includes stubs for base game Wwise events in the future.
The suggested approach in this heading may change once that process is complete.
====

Wwise project files require extra consideration to store in
xref:Development/BeginnersGuide/LearnGit.adoc[source control].
Distributing the raw audio assets is sometimes prohibited by audio licenses.

One approach is to create a separate (private) repository to store the Wwise project and to enable Git LFS for raw audio files.
However, this interferes with the typical one-repo-per-mod structure by tying multiple mod's files together in one repository.

Wwise offers advice on connecting to source control
https://www.audiokinetic.com/en/library/edge/?source=Help&id=using_wwise_with_source_control_system[in their documentation].
```

2025-01-07 17:19 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +TODO: Waiting for CSS to provide the correct audio bus names.
What should people do in the mean time? Do we currently know any of the audio bus names? These, for example? https://discord.com/channels/555424930502541343/601030071221878784/1294145591709794379

2025-01-07 22:40 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +Once the AK event has ended, you must clean up the `AK Component` using the callback event.
@budak7273 Correct. Technically, one AK component can trigger multiple AK events simultaneously.

So, if you want to trigger multiple events or just occasionally trigger an event, it's best to add an AK Component to the actor.

2025-01-07 22:43 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +=== Setting Up Attenuation
Yeah, stuff like UI and ADA messages won't require attenuation. I'm going to add steps to set this up, as the video feels a bit of a cop-out.

2025-01-08 00:16 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +=== Setting Up Attenuation
Updated the docs to include setting up attenuation

2025-01-08 00:23 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +TODO: Waiting for CSS to provide the correct audio bus names.
ATM, the master audio bus that Wwise has by default, correctly links to the in-game Master volume slider. This is currently the only way to change the volume of Wwise audio.

The variables linked to that Discord message are RTPC variables and not the names of the Audio Buses. I have tried a few different combinations of those just incase it worked. But this did not work. We will need to wait for CSS to provide the names of the Audio Buses.

2025-01-11 00:28 UTC, mrhid6 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +Once the AK event has ended, you must clean up the `AK Component` using the callback event.
Speaking with Arch, the AK component for both fire and forget and AK component attached to the component will be destroyed once the actor is destroyed.

2025-01-26 17:39 UTC, budak7273 requested changes

2025-01-26 17:39 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +Trying to play more than this limit will result in lower-priority sounds like footsteps, music, or animal sounds playing.
Did this get flipped? I would expect higher-priority sounds to be played in this situation, not the lower priority ones.

2025-01-26 17:39 UTC, budak7273 commented on modules/ROOT/pages/Development/Satisfactory/Audio.adoc
> +For fire and forget ak events, use the `Get Is Significant` function before posting the event:
```suggestion
For fire and forget AK events, use the `Get Is Significant` function before posting the event:
```

2025-01-26 19:52 UTC, merged