Added LICENSE
satisfactorymodding/Documentation pull request #96
Opened 2021-12-08 18:26 UTC by Preston159

2021-12-08 18:39 UTC, Vilsol requested changes
There is a bigger issue than just adding a file called `LICENSE` to the repository. We must first request every previous contributor to agree to this license before we can enforce it. Have you done this?

2021-12-08 18:39 UTC, Vilsol commented on LICENSE
> +    Copyright (C) <year>  <name of author>
Missing information

2021-12-08 18:39 UTC, Vilsol commented on LICENSE
> +    <program>  Copyright (C) <year>  <name of author>
Missing information

2021-12-08 19:53 UTC, Preston159 commented
Firstly, those lines in the license file are not meant to be modified (and, in fact, cannot be). They exist as examples of what should be displayed _in_ your program.

```
Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.
```

Regarding the requirement that contributors agree, I think we'd only need 3 of the existing contributors to agree:

- @Vilsol 
- @Panakotta00 
- @budak7273 

As far as I can tell, these are the only three people who have made contributions outside of the documentation/website, which already states at the bottom that it is licensed under GPLv3; this is why I chose the same license. If I'm incorrect about any of this, please let me know.

2021-12-08 20:01 UTC, Vilsol commented
When you are referencing `documentation/website`, what are you referring to specifically?

Also, we would have to get confirmation from all of [these](https://github.com/satisfactorymodding/Documentation/graphs/contributors) contributors, as a root license would apply to everything in the repository.

2021-12-08 20:09 UTC, Preston159 commented
In the footer of https://docs.ficsit.app/ it states

> Except where otherwise noted, docs.ficsit.app is licensed under the GNU General Public License v3.0 (GPLv3).

Unless there exists content served on the website that states otherwise, I take this to mean everyone who has contributed in the `modules` and `supplemental-ui` folder has already agreed to the GPLv3 license.

2021-12-08 20:13 UTC, aaomidi commented
> Unless there exists content served on the website that states otherwise, I take this to mean everyone who has contributed in the modules and supplemental-ui folder has already agreed to the GPLv3 license.

https://github.com/satisfactorymodding/Documentation/tree/9ed77e86b9889f1b5f1b938726ea391164604c7d

IANAL. This is where that language was introduced, anything before that point will need permissions from contributors most likely.

2022-03-27 00:12 UTC, Feyko commented
Closing this because of [this](https://github.com/satisfactorymodding/Documentation/pull/96#issuecomment-989152231) comment, the following mini-thread about the current effective License and inactivity

2022-03-27 00:12 UTC, closed without merging